/**
 * Lista de términos bloqueados para alias de jugadores.
 * Cubre español general, colombiano y inglés común.
 * La comparación es case-insensitive e incluye substrings.
 */
export const PROFANITY: readonly string[] = [
  // ── Español general ──────────────────────────────────────────────────────
  'puta',
  'puto',
  'putos',
  'putas',
  'mierda',
  'mierdas',
  'culo',
  'culos',
  'coño',
  'pene',
  'penes',
  'vagina',
  'perra',
  'perro',
  'verga',
  'vergas',
  'picha',
  'pollas',
  'polla',
  'cabron',
  'cabrona',
  'pendejo',
  'pendeja',
  'pendejos',
  'idiota',
  'imbecil',
  'gilipollas',
  'marica',
  'maricon',
  'joder',
  'hostia',
  'follar',
  'chinga',
  'chingada',
  'mamada',
  // ── Colombiano / latinoamericano ─────────────────────────────────────────
  'gonorrea',
  'malparido',
  'malparida',
  'hijueputa',
  'hijuepucha',
  'hdp',
  'guevon',
  'guevona',
  'huevon',
  'cagada',
  'sapo',
  'mamagüevo',
  'mamagüeva',
  'pirobos',
  'pirobo',
  'camello',
  'mojon',
  'mojona',
  'berraco',
  // ── Inglés ────────────────────────────────────────────────────────────────
  'fuck',
  'fucker',
  'fucking',
  'shit',
  'bitch',
  'bitches',
  'cunt',
  'cock',
  'cocks',
  'dick',
  'dicks',
  'pussy',
  'ass',
  'asses',
  'asshole',
  'nigger',
  'nigga',
  'fag',
  'fags',
  'faggot',
  'whore',
  'whores',
  'slut',
  'sluts',
  'bastard',
  'motherfucker',
  'retard',
  // ── Genéricos ────────────────────────────────────────────────────────────
  'sex',
  'sexo',
  'porn',
  'porno',
  'xxx',
  'rape',
  'nazi',
  'hitler',
];

export function containsProfanity(text: string): boolean {
  const lower = text.toLowerCase();
  return PROFANITY.some((word) => lower.includes(word));
}
